---
namespace: warpcode
name: cluster_config
description: Collection of roles to setup my server cluster environment
version: "1.0.0"
readme: README.md

authors:
  - warpcode

license:
  - MIT
tags:
  - pc
  - gaming
  - cli
  - macos
  - tools
  - osx
  - homebrew
  - brew
  - workstation
  - dev
  - mas
  - appstore
  - apps
  - configure
  - development
  - apple
  - ios
  - macbook
  - imac
  - macmini
  - server

repository: https://github.com/warpcode/cluster-config
documentation: https://github.com/warpcode/cluster-config
homepage: https://github.com/warpcode/cluster-config
issues: https://github.com/warpcode/cluster-config/issues

build_ignore: []

dependencies:
  community.general: ">=3.0.0"
