---
- name: Disable enterprise repo
  apt_repository:
    filename: pve-enterprise
    repo: "deb https://enterprise.proxmox.com/debian/pve {{ pve_distribution }} pve-enterprise"
    state: absent
    update_cache: yes

- name: Enable community repo
  apt_repository:
    filename: pve-community
    repo: "deb http://download.proxmox.com/debian/pve {{ pve_distribution }} pve-no-subscription"
    state: present
    update_cache: yes
